### ISSUE TITLE
Add support for vfork()?

### ISSUE THREAD

**Issue by ton** [DaanDeMeyer/reproc#10]
Have you considered either using `vfork()` instead of `fork()` or adding support for `vfork()` as an alternative to `fork()` for the POSIX implementation?

We are using a hand-rolled process library at my current employer that is based on Folly's subprocess implementation. We depend on `vfork()` since we occassionally have to fork huge processes.

There are some drawbacks over `fork()` especially in a multi-threaded context. Some helpful information: http://ewontfix.com/7/

**Comment by DaanDeMeyer** [comment]
It should definitely be possible to support calling vfork instead of fork.

Should both fork and vfork be supported at the same time? I'd prefer not to complicate the API with an extra option so it'd be ideal if `fork` could just be replaced by `vfork` at compile time using a preprocessor define. Of course this isn't possible if you need both at runtime.

**Comment by ton** [comment]
In our case, we only need `vfork()` at runtime, but of course for other use cases this might not be the case.

**Comment by DaanDeMeyer** [comment]
I'm thinking of adding a bitflags parameter to `reproc_start` so other parameters like this can be added in the future without changing the function parameters.

As for the implementation, do we just call `vfork` instead of `fork` and apply the signals workaround if `vfork` is used? I don't think anything I do after forking modifies the parent since I only operate on file descriptors which are copied to the child process so closing them won't affect the parent. There's also the `setpgid` call but I think that's safe to call as well. I'm not sure if there are any other `vfork` caveats we need to be aware of.

**Comment by DaanDeMeyer** [comment]
I found this very well documented example of safely calling vfork: https://bugzilla.redhat.com/attachment.cgi?id=941229

Only annoyance is that blocking the signals requires `pthread_sigmask` when multiple threads are used which implies having a pthread dependency.

I had a look at folly's implementation and it's similar to reproc's except they default to `vfork` with `pthread_sigmask`. Maybe reproc should do the same, except we would check if pthread is available and use `sigprocmask` if it isn't. We can work around the signals problem by blocking the signals but we'll have to add a note to the readme about the `set*id` calls.

**Comment by DaanDeMeyer** [comment]
We now default to `vfork` (except for timeout forks which need a normal `fork`). We do have a required dependency on `pthreads` now which could be relaxed to an optional dependency if threads aren't available but I don't think anyone is using reproc on POSIX systems without pthreads so I'm not inclined to change it until someone asks for it.

Does this solve the issue for you?

**Comment by ton** [comment]
Great, thank you! Now I am curious to see what changes you did to get there :)

**Comment by DaanDeMeyer** [comment]
https://github.com/DaanDeMeyer/reproc/blob/c1f388ab66cb1f9645cbbf0855ba7123c9c28dcf/reproc/src/posix/process.c#L36

The linked if statement contains all `vfork` specific code. It's pretty much just an adapted version of the safe `vfork` example from redhat.
