### ISSUE TITLE
Reproc linked to Threads::Threads?

### ISSUE THREAD

**Issue by Alzathar** [DaanDeMeyer/reproc#13]
What is the reason to link Reproc to Threads::Threads?

**Comment by DaanDeMeyer** [comment]
In reproc 3.0.0, process spawning was changed to use `vfork` instead of `fork`. However, to use `vfork` safely, signals have to be masked in the parent process before calling `vfork` (See <https://bugzilla.redhat.com/attachment.cgi?id=941229> for the `vfork` spawning code reproc's spawning code is based on). It is possible to mask signals using `sigprocmask` but its behaviour is undefined in multithreaded processes. pthreads provides `pthread_sigmask` which is just like `sigprocmask` but with defined behaviour in multithreaded processes. Since reproc might be used in a multithreaded process, I opted to use `pthread_sigmask` and link to pthreads since I assumed it would be available on all platforms reproc would be used on.

We switched to `vfork` instead of `fork` because it can result in a performance increase when spawning child processes in very large (memory-intensive) parent processes.

**Comment by Alzathar** [comment]
Thanks for the clarification. Using a custom CMakelists.txt I compiled `reproc` without linking it to `Threads::Threads` under Windows 10 and Visual Studio 2017 (64-bit). Doest it mean this dependency is only necessary for Unix compiler?

I am able to used `reproc` with`Threads::Threads` linked to it under Visual Studio 2017. But then external projects dependent of `reproc` have also to be linked to `Threads::Threads` which is not found without explicitly call the CMake `FindPackage(Threads)` command in the external projects. 

Have you the same effect?

**Comment by DaanDeMeyer** [comment]
Threads::Threads is only really necessary on UNIX but since `FindPackage(Threads::Threads)` is basically a noop on Windows I didn't special case it for UNIX only.

It shouldn't be necessary to explicitly call ``find_package(Threads)` when using reproc via `add_subdirectory(reproc)` or `find_package(reproc)`. Both methods should automatically handle calling `find_package(Threads)` for you.

**Comment by Alzathar** [comment]
I also compiled reproc without `Threads::Threads` under macOS 10.12 and it works like a charm.

**Comment by DaanDeMeyer** [comment]
Yes, it seems pthreads is linked automatically on macOS without requiring any compiler flags.

Is there any change you want to be made to reproc itself?

**Comment by Alzathar** [comment]
Everything is fine. Thank you for this great library! 

I wanted to report the linking issue in case other people might have this problem under Windows.

**Comment by DaanDeMeyer** [comment]
reproc 7.0.0 has just been released which introduces the `REPROC_MULTITHREADED` option that allows configuring whether reproc should link against pthreads. It is enabled by default but can be disabled if you're certain your code won't use multiple threads.
