### ISSUE TITLE
Child disown (detach) support

### ISSUE THREAD

**Issue by silverclaw** [DaanDeMeyer/reproc#2]
I'm currently writing a daemon-like server where each connection can often crash (it's a server meant for running tests). I use forks to allow tests to die (segfaults for example) but keeping the server still accepting new connections.
There's not a lot of child management going on, besides trivial connection setup, so a reference to child connections (processes) at some point becomes irrelevant. One could simply leave the children to their own devices, but being unable to detach from them stops the process from being killed (it becomes a zombie), and thus a server can't be restarted as the current running one never "terminates".

This isn't at all important for my own project right now, but it would be something nice to have :)

**Comment by DaanDeMeyer** [comment]
Is the idea to just fire and forget connection processes? While it should be possible to add this to reproc, it feels a little bit out of scope to me. Is it not possible to keep a list of processes that you wait for when the server exits?

**Comment by silverclaw** [comment]
That is what I currently do, and its "ok". However, consider that the server configuration needs to be changed (or even the binary replaced). One normally just SIGTERM or SIGKILL the server process and restart it. But if it becomes zombie, then you can't really waitpid on it. Although technically I can execve to implement this functionality.

Also, while in my particular case is fire-and-forget, one might want to do some setup on the child process before "forgetting".

I should re-iterate that this is simply a nice-to-have, but by no means a hard requirement for me to use this fantastic library :)

**Comment by DaanDeMeyer** [comment]
At the moment I have no idea what should be in the API for detaching and what shouldn't be. I'd like to wait until there's some more use cases for it before getting around to implementing it so all common use cases can be properly supported.

I'll leave the issue open so people looking for detaching support can add their specific use case here.

**Comment by Alzathar** [comment]
FYI: Qt proposed with Qt 5.10 a new API for detached support: http://blog.qt.io/blog/2017/08/25/a-new-qprocessstartdetached/

For specific use case, I can see the case where you want to restart your application (using an embedded console or a menu action, or due to an internal error, etc.). A simple `std::system` might not be enough in case you want to set a working directory.

**Comment by DaanDeMeyer** [comment]
Thanks for linking that Qt blog post. There's some good information in there.

From what I gather from the Qt blog post, the main use case for detaching is
processes that need to outlive the calling process. While this is possible with
the current reproc API by explicitly not stopping the process it's absolutely
not recommended since it will lead to resource leaks. The solution is likely (as
mentioned in the Qt article) to daemonize the detached process which does allow
for complete resource cleanup even if the calling process exits.

One thing I'm not sure about is what to do with the output of the detached
process. When detaching the calling process is not guaranteed to receive all
child process output anymore since it might exit before the child process. This
means we'd have to support alternative redirection options for
stdin/stdout/stderr that don't redirect output or redirect the output to a file.
If these alternatives have to be supported next to the already existing
mechanism (redirecting to pipes) reproc's API would become a lot less intuitive
since we'd be supporting two completely different use cases with a single API.

As an example, if we added support to `reproc_start` for redirecting the
standard streams output to files and detaching the child process, `reproc_read`
and `reproc_stop` wouldn't have any use anymore (but would still appear in the
API since they are necessary when output is redirected to pipes and the process
is not detached).

To get around this, I'd like to develop a separate API for detached processes
that doesn't provide functions for reading from the detached process in the
calling process (but does allow redirecting output to a file) and doesn't
provide any function for stopping the detached process. As an example: the C API
could reside in `reprocd.h` (reproc daemon) and the C++ wrapper for this API
would be `reproc::daemon`.

The biggest downside of this approach would be that it wouldn't be possible to
read the output of a detached process directly in the calling process. You could
still get the output by redirecting the detached process stdout/stderr output to
files and reading from that file if really needed.

Any feedback is highly appreciated.

**Comment by Alzathar** [comment]
I think you can keep the pipes redirection for detached process. The main point is that you have to use the interprocess communication (IPC) using named pipe and possibly shared memory for that. You will have to create a named pipe between the parent process and the daemon, while the daemon creates an (anonymous) pipe with the detached process(es) to redirect the streams (stdout, stderr, stdin). In case the parent process wants to communicates with the detached process(es), it has to pass by the daemon. Internally, the `reproc`library will have to manage the IPC. This should be transparent to the developer. Commands can be send to the daemon using the named pipe and the result are written in a shared memory. Of course an acknowledgement is sent by the daemon to the parent process to tell it that the shared memory was written.

![untitled diagram-2](https://user-images.githubusercontent.com/2211202/47862423-7670be80-ddcb-11e8-983b-804b7128ca1f.png)

**IPC commands**
 - `REPROCD_READ_OUT`: the parent process requests to the daemon to read the content of its stdout buffer.
 - `REPROCD_READ_ERR`: the parent process requests to the daemon to read the content of its stderr buffer.
 - `REPROCD_WRITE_IN`: the parent process requests to the daemon to write the content of its stdin buffer.
 - `REPROCD_QUIT`: the parent process requests to the daemon to quit (clean the resource, remove the pipes, etc.).
 - `REPROCD_IS_ALIVE`: the parent process requests to the daemon to verify if the detached process is still running
 - `REPROCD_ACK` : message sent by the daemon to the parent process to tell it the command was a success
- `REPROCD_FAILURE`: message sent by the daemon to the parent process to tell it the command failed (e.g impossible to write in the shared memory)

**Possible scenarios**
 - The parent process outlives the detached process: the parent process can send the command `REPROCD_IS_ALIVE` to determine if the detached process is still running. if this not the case, the parent process can send the command `REPROCD_QUIT` to the daemon to quit prematurely.
 - The detached process outlives the parent process:  the parent process send the command `REPROCD_QUIT` when it quits. The daemon quits and the detached process will continue to run. No resources leaks will happen.

**Comment by DaanDeMeyer** [comment]
One problem with this design is that the detached processes will be connected to closed pipes when the daemon is closed. I don't think this is safe since it might cause failing writes to happen in the detached processes when they write to stdout or stderr. That's why redirecting to files seems like a good idea to me. Those files won't disappear when the parent process exits which allows the detached processes to keep operating normally.

**Comment by DaanDeMeyer** [comment]
I'm going to close this one as I think it's out of scope for reproc. Detached processes would require a completely different API and I'm pretty sure I wouldn't be able to reuse any of the internal code either. As such, I think it's best to keep reproc focussed on processes whose lifetime does not exceed the lifetime of the parent process.
