### ISSUE TITLE
not compiling anymore

### ISSUE THREAD

**Issue by Milerius** [DaanDeMeyer/reproc#25]
hello the line `auto ec = registry_.at(coin).background.start(args, tools_path_.string().c_str());`

is not compiling for me anymore:

```
/Users/romanszterg/CLionProjects/antara-gaming-sdk/modules/blockchain/antara/gaming/blockchain/nspv.system.cpp:60:61: fatal error: reference to type 'const reproc::options' could not bind to an rvalue of type 'const std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::value_type *' (aka 'const char *')
        auto ec = registry_.at(coin).background.start(args, tools_path_.string().c_str());
                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/romanszterg/CLionProjects/antara-gaming-sdk/cmake-build-debug-sfml/_deps/reproc-src/reproc++/include/reproc++/reproc.hpp:91:56: note: passing argument to parameter 'options' here
                                        const options &options = {}) noexcept;
```

**Comment by Milerius** [comment]
There is not working directory anymore ?

**Comment by Milerius** [comment]
I will assume that


`auto ec = registry_.at(coin).background.start(args, reproc::options{nullptr,tools_path_.string().c_str()});`

Is what I want

**Comment by Milerius** [comment]
But I'm surprise you seem's to use SemVer

This change is a breaking one but the SemVer Major version is not updated, that's why I'm surprised

**Comment by DaanDeMeyer** [comment]
I don't update the major version for each separate breaking change. When I decide to do a release and I've done breaking changes since the last release, I release a new major version. Of course, if you're following the master branch, each commit can possibly break backwards compatibility. The set of breaking changes you're experiencing now will be part of reproc 10.0.0

The solution you posted is indeed how a custom working directory should be specified now.

**Comment by Milerius** [comment]
Ok thanks !
